# Data on Overindebtedness in Germany from Creditreform 

https://www.creditreform.de/aktuelles-wissen/pressemeldungen-fachbeitraege/show/schuldneratlas-deutschland-2018, last retrieved 2019-07-31.

In [8]:
def umlaut(string):
    """
    This function replaces replcaces umlaut-code with letter in utf-8. 
    This is useful, when detect function from chardet module does not 
    work.
    dirk.ulbricht@gmail.com, 20.9.2019
    """
    string = re.sub('Ã¼', 'ü',string)
    string = re.sub('ÃŸ', 'ß', string)
    string = re.sub('Ã¶', 'ö', string)
    string = re.sub('Ã¤', 'ä', string)
    return string

In [16]:
import pandas as pd
import numpy as np
import re
import os

In [3]:
ls = os.listdir('foo')
ls

['foo-page-9-table-1.csv',
 'foo-page-5-table-1.csv',
 'foo-page-6-table-1.csv',
 'foo-page-10-table-1.csv',
 'foo-page-3-table-1.csv',
 'foo-page-4-table-1.csv',
 'foo-page-8-table-1.csv',
 'foo-page-1-table-1.csv',
 'foo-page-2-table-1.csv',
 'foo-page-11-table-1.csv',
 'foo-page-7-table-1.csv']

In [23]:
creditreform = pd.read_csv('foo/foo-page-1-table-1.csv',header=[0,1],decimal=',')
for i in range(2,len(ls)+1):
    creditreform_add = pd.read_csv('foo/foo-page-'+str(i)+'-table-1.csv',header=[0,1],decimal=',')
    creditreform = creditreform.append(creditreform_add)

In [24]:
creditreform.head()

,g \n \n \nNr.,Kreise und kreisfreie Städte,Bundesland,Unnamed: 3_level_0,Schuldnerquoten in %,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Typ 2013,2014,2015,2016,2017,2018
0,1.,"Aachen, Städteregion",Nordrhein-Westfalen,SV,11.02,11.06,10.94,11.21,11.11,11.18
1,2.,Ahrweiler,Rheinland-Pfalz,LK,8.72,8.60,8.32,8.61,8.65,8.67
2,3.,Aichach-Friedberg,Bayern,LK,5.27,5.19,5.17,5.58,5.62,5.61
3,4.,Alb-Donau-Kreis,Baden-Württemberg,LK,5.72,5.80,5.90,6.22,6.38,6.49
4,5.,Altenburger Land,Thüringen,LK,8.29,8.66,8.72,8.84,8.87,8.95

In [25]:
creditreform.columns = ['nr', 'region', 'state', 'state_abbrev', 'debt_2014', 'debt_2015', 'debt_2016'
                        , 'debt_2017', 'debt_2018', 'debt_2019']

In [27]:
sum(creditreform.state == 'NaN')

0

In [31]:
creditreform[creditreform.state.isna(),:]

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [46]:





creditreform = creditreform.dropna()

# some state-level information needs to be skipped
creditreform = creditreform[creditreform.state != 'Bundesland']

# Umlaute couldn*t be dealt with using encoding and detect (see functions at top of notebook) therefore:
# correct for wrong reading of German "Umlaute"
creditreform['region'] = creditreform['region'].apply(umlaut)
creditreform['state'] = creditreform['state'].apply(umlaut)

creditreform['debt_2013'] = creditreform['debt_2013'].str.replace(',','.').astype(float)
creditreform['debt_2014'] = creditreform['debt_2014'].str.replace(',','.').astype(float)
creditreform['debt_2015'] = creditreform['debt_2015'].str.replace(',','.').astype(float)
creditreform.shape # There are 401 regions and here are 401 lines

creditreform.set_index('region',inplace=True)
creditreform.rename(index={
    'Aachen, Städteregion': 'Städteregion Aachen',
    'Baden-Baden, Stadtkreis': 'Baden-Baden, Stadt',
    'Düren, Kreis': 'Düren',
    'Freiburg im Breisgau, Stadtkreis': 'Freiburg im Breisgau, Stadt',
    'Heidelberg, Stadtkreis': 'Heidelberg, Stadt',
    'Heilbronn, Stadtkreis': 'Heilbronn, Stadt',
    'Karlsruhe, Stadtkreis': 'Karlsruhe, Stadt',
    'Kleve, Kreis': 'Kleve',
    'Ludwigshafen am Rhein, kreisfr. Stadt': 'Ludwigshafen am Rhein, kreisfreie Stadt',
    'Mannheim, Stadtkreis': 'Mannheim, Universitätsstadt',
    'Mettmann, Kreis': 'Mettmann',
    'Neustadt a.d. Weinstraße, Stadt': 'Neustadt an der Weinstraße, kreisfreie Stadt',
    'Pforzheim, Stadtkreis': 'Pforzheim, Stadt', 
    'Schwabach': 'Schwabach, Stadt',
    'Stuttgart, Stadtkreis': 'Stuttgart, Landeshauptstadt', 
    'Ulm, Stadtkreis': 'Ulm, Universitätsstadt',
    'Viersen, Kreis': 'Viersen',
    'Wesel, Kreis': 'Wesel',
    'Deutschland': 'Bundesgebiet'
},inplace=True)
creditreform.reset_index(inplace=True)

# adding change column
creditreform['ove18_13']=creditreform['debt_2018']-creditreform['debt_2013']
creditreform = creditreform.drop(columns='nr')
creditreform.to_csv('creditreform.csv', index=False)
creditreform.head()

,region,state,state_abbrev,debt_2013,debt_2014,debt_2015,debt_2016,debt_2017,debt_2018,ove18_13
0,Städteregion Aachen,Nordrhein-Westfalen,SV,11.02,11.06,10.94,11.21,11.11,11.18,0.16
1,Ahrweiler,Rheinland-Pfalz,LK,8.72,8.60,8.32,8.61,8.65,8.67,-0.05
2,Aichach-Friedberg,Bayern,LK,5.27,5.19,5.17,5.58,5.62,5.61,0.34
3,Alb-Donau-Kreis,Baden-Württemberg,LK,5.72,5.80,5.90,6.22,6.38,6.49,0.77
4,Altenburger Land,Thüringen,LK,8.29,8.66,8.72,8.84,8.87,8.95,0.66

In [47]:
creditreform_variable_description = pd.DataFrame({
    'Variable' : list(creditreform.columns[creditreform.columns.str.contains('debt')])
    ,'Beschreibung' : """Anteil Überschuldeter Erwachsener; 
                        Für eine genaue Beschreibung der Definition
                        siehe Originalquelle"""
    ,'Description' : """Percentage Share of overindebted adults. For
                        a detailed description of the critria applied
                        for consider adults overindebted see source."""
    ,'Quelle' : 'Creditreform, SchuldnerAtlas 2018'
    ,'Source' : 'Creditreform, SchuldnerAtlas 2018'
})
creditreform_variable_description = creditreform_variable_description.append({'Variable':'ove18_13'
                                         ,'Beschreibung':'Differenz von debt_2018 und debt_2013'
                                         ,'Description':'Difference of debt_2018 and debt_2013'
                                         ,'Source':'Creditreform, SchuldnerAtlas 2018'
                                         ,'Quelle':'Creditreform, SchuldnerAtlas 2018'},ignore_index=True)
creditreform_variable_description = creditreform_variable_description.append({'Variable':'state'
                                         ,'Beschreibung':'Deutsche Ländernamen'
                                         ,'Description':'German state names'
                                         ,'Source':'Creditreform, SchuldnerAtlas 2018'
                                         ,'Quelle':'Creditreform, SchuldnerAtlas 2018'},ignore_index=True)
creditreform_variable_description.to_csv('creditreform_variable_description.csv'
                                         , index=False
                                        ,sep=';')
creditreform_variable_description

,Variable,Beschreibung,Description,Quelle,Source
0,debt_2013,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
1,debt_2014,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
2,debt_2015,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
3,debt_2016,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
4,debt_2017,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
5,debt_2018,Anteil Überschuldeter Erwachsener; \n ...,Percentage Share of overindebted adults. For\n...,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
6,ove18_13,Differenz von debt_2018 und debt_2013,Difference of debt_2018 and debt_2013,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"
7,state,Deutsche Ländernamen,German state names,"Creditreform, SchuldnerAtlas 2018","Creditreform, SchuldnerAtlas 2018"