http://www.statistik-nord.de/fileadmin/maps/Stadtteil_Profile_2018/atlas.html

In [4]:
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as stats
import re
import camelot

In [ ]:
StPrf18 = pd.read_excel('Stadtteilprofile2018.xlsx', index_col=0, skiprows=0, header=3)
#stprofil.head()

# Results of the most recent European Elections in Germany (2019). 
Source: https://www.bundeswahlleiter.de/europawahlen/2019/ergebnisse.html (last accessed 2019-07-27).

Contains results for all cities and free regions for all 16 German Laender and aggregated Data for Laender.

In [ ]:
EuElect = pd.read_csv('ew19_kerg.csv',sep=';',skiprows=[0],header=[1])#,index_col=-1)
EuElect = EuElect[EuElect.isnull().Nr==False]
EuElect.set_index('Nr',inplace=True)
EuElect.head()

In [ ]:
# Getting AfD 2019 and 2014
AfD_colname=list(EuElect.columns.str.contains('Alternative'))
AfD_colind = np.where(AfD_colname)[0][0]
election = EuElect.iloc[:, [a for a in np.arange(10)]+[AfD_colind, AfD_colind+1]]
# columns in German
election.columns = ['Gebiet'
              , 'gehört zu'
              , 'Wahlberechtigte 2019'
              , 'Wahlberechtigte 2014'
              , 'Wähler/-innen 2019'
              , 'Wähler/-innen 2014'
              , 'Ungültige 2019'
              , 'Ungültige 2014'
              , 'Gültige 2019'
              , 'Gültige 2014'
              , 'AfD 2019'
              , 'AfD 2014']
election.columns = ['region'
              , 'subregion'
              , 'eligible_voters_19'
              , 'eligible_voters_14'
              , 'voters_19'
              , 'voters_14'
              , 'invalid_19'
              , 'invalid_14'
              , 'valid_19'
              , 'valid_14'
              , 'af_19'
              , 'afd_14']
# creating a common index for merge later on
election.index = [str(int(a)) for a in election.index]

election.shape
election.head()

## Regional Data on unemployment and population statistics
Source: https://www.regionalstatistik.de, last accessed: 2019-07-27.
Unemployment Data ("13211-02-05-4.xlsx" is for 2018, most recent data.

In [ ]:

unemployment = pd.read_excel('13211-02-05-4.xlsx',index_col=0,header=[2,3,4])

# eliminating empty rows
unemployment = unemployment[unemployment.iloc[:,2].isnull()==False]

#unemployment.columns
#[re.sub('^0','',index) for index in unemployment.index]
index_new=[]
for i in range(len(unemployment)): 
    index_new.append(re.sub('^0','',unemployment.index[i])) 
unemployment.index = index_new




unemployment.columns= [
                 'Gebiet'
                , 'Arbeitslose'
                , 'Arbeitslose Ausländer'
                , 'Arbeitslose Schwerbehinderte'
                , 'Arbeitslose 15-20 Jährige'
                , 'Arbeitslosse 15-25 Jährige'
                , 'Arbeitslose 55-65 Jährige'
                , 'Langzeitarbeitslose'
                , 'AL-Quote abh. zivile Erwerbspersonen'
                , 'AL-Quote alle zivilen Erwerbspersonen'
                , 'AL-Quote alle zivilen Erwerbspersonen, Männer'
                , 'AL-Quote alle zivilen Erwerbspersonen, Frauen'
                , 'AL-Quote alle zivilen Erwerbspersonen, Ausländer'
                , 'AL-Quote alle zivilen Erwerbspersonen, 15-25'
                    ]
unemployment.head(50)
unemployment.rename(index={'DG':'99'}, inplace=True)

#unemployment.columns
#unemployment.shape

In [ ]:
df = election.merge(unemployment, left_index=True, right_index=True, how='left')#, indicator=True)# indicator=True)#, how='outer') 

df.rename(columns={'Gebiet_x':'Gebiet'},inplace=True)
df.drop(labels=['2000','11000'],inplace=True)
df.index.contains('Bremen')
#df.head()

### Employment on a regional level

In [ ]:
employment = pd.read_excel('13312-01-05-4.xlsx'
                           , header=[3]
                           
                           , skip=[0,1]
                          )
employment.reset_index(inplace=True)
employment.rename(columns={'level_0':'region', 'Insgesamt':'employment 2017'}, inplace=True)


employment = employment.iloc[2:540,:]
employment = employment[['region', 'employment 2017']]
employment.region[employment.region=='DG']="99"
employment.set_index('region', inplace=True)
index_new=[]
for i in range(len(employment)): 
    index_new.append(re.sub('^0','',employment.index[i]))
employment.index = index_new
employment.head(20)
#employment.shape
df_new = df.merge(employment, left_index=True, right_index=True, how='outer', indicator=True)
df_new[df_new._merge=='left_only']
#df.loc['11']

In [ ]:
re.sub('^0','',employment.index[10])
employment.head()

In [ ]:
df[df._merge=='left_only']

In [7]:
import tabula 
creditreform = tabula.read_pdf("aaa.pdf",pages=1)
tabula.convert_into("aaa.pdf", "aaa.xlsx", output_format="xlsx")
#read_pdf(“offense.pdf”)
#pd.read_pdf("SchuldnerAtlas-2018-nach-Kreisen-alphabetisch.pdf")

Error:

CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\dirku\\Anaconda3\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar', '--pages', '1', '--guess', '--outfile', 'C:\\Users\\dirku\\AppData\\Local\\Temp\\tmpwpj84u6b', 'aaa.pdf']' returned non-zero exit status 1.

In [60]:

# importing required modules 
import PyPDF2 
  
# creating a pdf file object 
pdfFileObj = open('SchuldnerAtlas-2018-nach-Kreisen-alphabetisch.pdf', 'rb') 
  
# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 
  
# printing number of pages in pdf file 
n_pages = pdfReader.numPages
for i in range(9):
    
    # creating a page object 
    pageObj = pdfReader.getPage(i) 
  
    # extracting text from page 
    testtext = pageObj.extractText()

    csvname = 'page_'+str(i)+'.csv'
    with open(csvname, 'w') as f:
        a = 0
        for line in testtext:
            if (i==10)&a==1562:
                pass
            else:
                f.write(line)
                a +=1
  
pdfFileObj.close()

fertig

In [67]:
page = pd.read_csv('page_0.csv', decimal=b',' ,skiprows=9)
page.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 21, saw 3

In [9]:
tables[0].df.head()

,0,1,2,3,4,5,6,7,8,9
0,g,,,,,,Schuldnerquoten in %,,,
1,Nr.,Kreise und kreisfreie Städte,Bundesland,,Typ 2013,2014,2015,2016,2017,2018
2,385.,Wesermarsch,Niedersachsen,LK,"11,10","11,27","11,17","11,27","11,25","11,14"
3,386.,Westerwaldkreis,Rheinland-Pfalz,LK,"10,77","10,94","10,66","11,01","10,98","10,91"
4,387.,Wetteraukreis,Hessen,LK,"9,75","9,92","9,87","9,88","9,77","10,07"

In [11]:
import camelot
#for i in range(11):
    #pagestr=str(i)
tables = camelot.read_pdf('SchuldnerAtlas-2018-nach-Kreisen-alphabetisch.pdf',flavor='stream', pages='1')
tables[0].df.head()
tables[0].df.to_csv('creditreform_1.csv')
#exportname= str(i)+'.csv'
#tables.export('Seite_2.csv', f='csv')

In [14]:
type(str(j))

int

In [17]:
import camelot
for i in range(11):
    j = i + 1
    pagestr=str(j)
    tables = camelot.read_pdf('SchuldnerAtlas-2018-nach-Kreisen-alphabetisch.pdf',flavor='stream', pages=pagestr)
    csvname = 'creditreform_'+pagestr+'.csv'
    tables[0].df.to_csv(csvname, index=False)
#exportname= str(i)+'.csv'
#tables.export('Seite_2.csv', f='csv')

In [ ]:
tables = camelot.read_pdf('SchuldnerAtlas-2018-nach-Kreisen-alphabetisch.pdf',flavor='stream', pages='11')
csvname = 'creditreform_'+'11'+'.csv'
tables[0].df.to_csv(csvname, index=False)

In [96]:
tables[12].df
creditreform = tables[0].df
creditreform
tables[2].df

,0,1,2,3,4,5,6,7,8,9
0,g,,,,,,Schuldnerquoten in %,,,
1,Nr.,Kreise und kreisfreie Städte,Bundesland,,Typ 2013,2014,2015,2016,2017,2018
2,34.,"Berlin, Stadt",Berlin,KS,"13,12","13,02","12,99","12,74","12,63","12,42"
3,35.,Bernkastel-Wittlich,Rheinland-Pfalz,LK,"8,00","8,15","7,95","8,41","8,36","8,49"
4,36.,Biberach,Baden-Württemberg,LK,"6,03","6,17","6,30","6,52","6,61","6,73"
5,37.,"Bielefeld, Stadt",Nordrhein-Westfalen,KS,"11,50","11,42","10,94","11,45","11,35","11,35"
6,38.,Birkenfeld,Rheinland-Pfalz,LK,"10,26","10,52","10,44","10,75","10,79","10,84"
7,39.,Böblingen,Baden-Württemberg,LK,"6,72","6,85","6,96","7,10","6,96","6,85"
8,40.,"Bochum, Stadt",Nordrhein-Westfalen,KS,"11,97","12,23","12,33","12,56","12,46","12,60"
9,41.,Bodenseekreis,Baden-Württemberg,LK,"7,19","7,19","7,08","7,31","7,37","7,40"
10,42.,"Bonn, Stadt",Nordrhein-Westfalen,KS,"9,38","9,24","9,22","9,11","9,00","8,87"
11,43.,Börde,Sachsen-Anhalt,LK,"10,62","10,76","10,60","10,71","10,71","10,76"
12,44.,Borken,Nordrhein-Westfalen,K,"8,79","8,83","8,69","8,66","8,59","8,63"
13,45.,"Bottrop, Stadt",Nordrhein-Westfalen,KS,"11,09","11,48","11,79","11,72","11,77","11,73"
14,46.,"Brandenburg an der Havel, Stadt",Brandenburg,KS,"15,36","15,69","15,97","16,05","15,91","15,72"
15,47.,"Braunschweig, Stadt",Niedersachsen,KS,"10,62","10,47","10,22","9,87","9,61","9,67"
16,48.,Breisgau-Hochschwarzwald,Baden-Württemberg,LK,"7,02","7,04","7,08","7,29","7,31","7,25"
17,49.,"Bremen, Stadt",Bremen,KS,"12,67","12,69","12,76","12,67","12,60","12,51"
18,50.,"Bremerhaven, Stadt",Bremen,KS,"19,84","20,41","20,82","20,80","20,79","21,22"
19,51.,Burgenlandkreis,Sachsen-Anhalt,LK,"10,74","11,04","11,27","11,43","11,54","11,56"
20,52.,Calw,Baden-Württemberg,LK,"8,02","8,38","8,58","8,78","8,66","8,77"
21,53.,Celle,Niedersachsen,LK,"11,90","12,05","12,06","12,16","11,96","11,89"
22,54.,Cham,Bayern,LK,"5,88","5,97","5,89","6,04","6,07","6,08"
23,55.,"Chemnitz, Stadt",Sachsen,KS,"10,22","10,66","11,15","11,39","11,57","11,78"
24,56.,Cloppenburg,Niedersachsen,LK,"9,11","9,16","9,13","9,34","9,33","9,57"
25,57.,Coburg,Bayern,LK,"7,94","7,88","7,75","7,73","7,69","7,70"
26,58.,"Coburg, Stadt",Bayern,KS,"9,70","9,48","9,31","9,30","9,31","9,34"
27,59.,Cochem-Zell,Rheinland-Pfalz,LK,"7,69","7,66","7,53","8,05","8,21","8,43"
28,60.,Coesfeld,Nordrhein-Westfalen,K,"7,40","7,40","7,39","7,37","7,20","7,19"
29,61.,"Cottbus, Stadt",Brandenburg,KS,"11,08","11,21","11,20","11,41","11,65","11,39"
30,62.,Cuxhaven,Niedersachsen,LK,"10,88","10,92","10,89","10,43","10,77","10,73"
31,63.,Dachau,Bayern,LK,"6,14","6,10","6,18","6,17","6,22","6,17"
32,64.,Dahme-Spreewald,Brandenburg,LK,"9,52","9,59","9,60","9,67","9,44","9,19"
33,65.,"Darmstadt, Wissenschaftsstadt",Hessen,KS,"9,23","8,93","8,97","8,98","8,88","8,70"
34,66.,Darmstadt-Dieburg,Hessen,LK,"8,31","8,39","8,45","8,64","8,58","8,55"
35,67.,Deggendorf,Bayern,LK,"6,92","6,89","6,99","7,28","7,58","7,45"
36,68.,"Delmenhorst, Stadt",Niedersachsen,KS,"15,53","15,59","15,46","15,32","15,34","15,57"
37,69.,"Dessau-Roßlau, Stadt",Sachsen-Anhalt,KS,"12,29","12,44","12,64","12,76","12,82","12,87"
38,70.,Diepholz,Niedersachsen,LK,"9,23","9,28","9,28","9,48","9,41","9,39"
39,71.,Dillingen a.d.Donau,Bayern,LK,"6,48","6,55","6,64","6,68","6,70","6,68"
40,72.,Dingolfing-Landau,Bayern,LK,"6,03","6,04","6,10","6,16","6,37","6,45"

In [15]:
import tkinter
tkinter._test()

In [16]:
import excalibur
excalibur.